"""empty message

Revision ID: 30980eaf0aba
Revises: ac984a5423c3
Create Date: 2022-10-31 03:35:54.615168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30980eaf0aba'
down_revision = 'ac984a5423c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('family_budgets_users_family_budget_id_fkey', 'family_budgets_users', type_='foreignkey')
    op.drop_constraint('family_budgets_users_user_id_fkey', 'family_budgets_users', type_='foreignkey')
    op.create_foreign_key(None, 'family_budgets_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'family_budgets_users', 'family_budgets', ['family_budget_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('personal_budgets_id_fkey', 'personal_budgets', type_='foreignkey')
    op.create_foreign_key(None, 'personal_budgets', 'users', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'personal_budgets', type_='foreignkey')
    op.create_foreign_key('personal_budgets_id_fkey', 'personal_budgets', 'users', ['id'], ['id'])
    op.drop_constraint(None, 'family_budgets_users', type_='foreignkey')
    op.drop_constraint(None, 'family_budgets_users', type_='foreignkey')
    op.create_foreign_key('family_budgets_users_user_id_fkey', 'family_budgets_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key('family_budgets_users_family_budget_id_fkey', 'family_budgets_users', 'family_budgets', ['family_budget_id'], ['id'])
    # ### end Alembic commands ###
